In [2]:
# NUMPY ARRAYS HAVE ELEMENTS OF SAME TYPE
import numpy as np

In [4]:
# how to create numpy arrays
l = [1,2,3]
np.array(l)

array([1, 2, 3])

In [6]:
l = [1,2,"3"]
np.array(l) # converts the whole list into string type elements even if one element is a string

array(['1', '2', '3'], dtype='<U11')

In [10]:
# np array of 10 zeros and ones
np.zeros(10)
a = np.ones(10, int) # pass the dtype you want it to be

print(a.dtype) # default is float64
a

# 2D np array
np.zeros((2,3))

# 3D np array
t = np.zeros((2,3,4))

# since i defined a to be an np array of ints, it changed "2" into int ka 2
a = np.zeros(10, int)
a[0] = "2"

a[1] = 3.4 # 3.4 ko 3 bana diya
a

# a[2] = "sanjana" # but ofc harr chiz ko int nahi bana payega (NOT ALLOWED)

int32


array([2, 3, 0, 0, 0, 0, 0, 0, 0, 0])

In [27]:
# accessing elements in np arrays
t[0][2]

# slicing
a[0:4]

# SHAPE
print(a.shape) # 1D ka shape
t.shape

c = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
c[0] # 0th row 

# [row information, column informartion] # : means all
c[:, 0] # 0th column 

c[0:2, 2:3]

(10,)


array([[3],
       [6]])

In [38]:
np.arange(10)

# numpy operations
a = np.array([1,2,3])
b = np.array([5,6,7])

print(a + 2) # add 2 to each element in np array 'a'
b * 3 # multiply 3 to each element in np array 'b'
a / 2 # divide by 2 each element in np array
a - 3 # subtract 3 from each element in np array 

a + b # element wise addition provided DIMENSIONS ARE SAME
a * b

[3 4 5]


array([ 5, 12, 21])

In [44]:
a.mean() # mean of elements 
a.sum() # sum of elements

# applying distance formula on arrays a and b
d = ((a - b) ** 2).sum() 
d # is the squared distance

import math as m
m.sqrt(d) #gives the distance

6.928203230275509

In [48]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[10,20],[30,40]])

a1.dot(a2) # multiplication of two matrices

# numpy matrices are STRICTLY 2D
np.mat([1,2,3])

matrix([[1, 2, 3]])

In [50]:
a = np.array([1,2,3])
b = np.array([10,20,30])
a.dot(b) # element wise multiplication and add i.e. 1*10 + 2*20 + 3*30

140

In [53]:
np.sum([[0, 1], [0, 5]], axis=1) # picks the 1st column

array([1, 5])